name: Validate PR and Create Jira Task

on:
  workflow_dispatch:
    inputs:
      SWAGGER_FILE:
        required: true
        type: string

jobs:
  download-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Swagger.yaml do Artifact
        uses: actions/download-artifact@v3
        with:
          name: swagger-file
          path: .

      - name: Verificar o Arquivo
        run: |
          if [ -f "swagger.yaml" ]; then
            echo "Swagger.yaml baixado com sucesso!"
            cat swagger.yaml
          else
            echo "Erro: Arquivo Swagger.yaml não encontrado!"
            exit 1
          fi

  PB33F:
    needs: download-swagger
    uses: ./.github/workflows/pb33f.yaml

  spectral:
    needs: PB33F
    uses: ./.github/workflows/spectral.yaml

  vale:
    needs: spectral
    uses: ./.github/workflows/vale.yaml

  jira:
    needs: vale
    uses: ./.github/workflows/jira.yaml
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
