name: Validate PR and Create Jira Task

on:
  workflow_call:
 
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código do PR
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
  