name: Validate PR and Create Jira Task

on:
  workflow_dispatch:
    inputs:
      SWAGGER_FILE:
        required: true
        type: string

jobs:
  prepare-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Criar arquivo temporário `temp_swagger.yaml`
        run: |
          echo "${{ github.event.inputs.SWAGGER_FILE }}" | base64 -d > temp_swagger.yaml
          echo "Arquivo `temp_swagger.yaml` criado com sucesso!"
      
      - name: Exibir conteúdo do arquivo (debug)
        run: cat temp_swagger.yaml

  PB33F:
    needs: prepare-swagger
    uses: ./.github/workflows/pb33f.yaml

  spectral:
    needs: PB33F
    uses: ./.github/workflows/spectral.yaml

  vale:
    needs: spectral
    uses: ./.github/workflows/vale.yaml

  jira:
    needs: vale
    uses: ./.github/workflows/jira.yaml
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
