name: Validate PR and Create Jira Task

on:
  workflow_dispatch:
    inputs:
      SWAGGER_FILE:
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código do PR
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

  PB33F:
    needs: checkout
    uses: ./.github/workflows/pb33f.yaml
    with:
      SWAGGER_FILE: ${{ inputs.SWAGGER_FILE }}

  spectral:
    needs: PB33F
    uses: ./.github/workflows/spectral.yaml
    with:
      SWAGGER_FILE: ${{ inputs.SWAGGER_FILE }}

  vale:
    needs: spectral
    uses: ./.github/workflows/vale.yaml

  jira:
    needs: vale
    uses: ./.github/workflows/jira.yaml
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
